var annotated_dup =
[
    [ "crypto", "namespacecrypto.html", [
      [ "AES128CFB8Cipher", "classcrypto_1_1AES128CFB8Cipher.html", "classcrypto_1_1AES128CFB8Cipher" ],
      [ "MinecraftHash", "classcrypto_1_1MinecraftHash.html", "classcrypto_1_1MinecraftHash" ],
      [ "ZLibCompressor", "classcrypto_1_1ZLibCompressor.html", "classcrypto_1_1ZLibCompressor" ]
    ] ],
    [ "luabridge", null, [
      [ "Stack< ClientState >", "structluabridge_1_1Stack_3_01ClientState_01_4.html", null ]
    ] ],
    [ "Angle", "classAngle.html", "classAngle" ],
    [ "ChatMessage", "classChatMessage.html", "classChatMessage" ],
    [ "CipherStream", "classCipherStream.html", "classCipherStream" ],
    [ "Client", "classClient.html", "classClient" ],
    [ "ClientConnectedEvent", "classClientConnectedEvent.html", null ],
    [ "ClientHandshakeEvent", "classClientHandshakeEvent.html", "classClientHandshakeEvent" ],
    [ "ClientSocket", "classClientSocket.html", "classClientSocket" ],
    [ "ClientStatusEvent", "classClientStatusEvent.html", "classClientStatusEvent" ],
    [ "Config", "classConfig.html", "classConfig" ],
    [ "EventHandler", "classEventHandler.html", "classEventHandler" ],
    [ "EventsManager", "classEventsManager.html", "classEventsManager" ],
    [ "Field", "classField.html", "classField" ],
    [ "File", "classFile.html", "classFile" ],
    [ "HandshakePacket", "classHandshakePacket.html", "classHandshakePacket" ],
    [ "IEntity", "classIEntity.html", "classIEntity" ],
    [ "IEvent", "classIEvent.html", "classIEvent" ],
    [ "ILiving", "classILiving.html", "classILiving" ],
    [ "IMCStream", "classIMCStream.html", "classIMCStream" ],
    [ "IPacket", "classIPacket.html", "classIPacket" ],
    [ "LoginStart", "classLoginStart.html", "classLoginStart" ],
    [ "LoginSuccess", "classLoginSuccess.html", "classLoginSuccess" ],
    [ "MemoryStream", "classMemoryStream.html", "classMemoryStream" ],
    [ "NetSocketStream", "classNetSocketStream.html", "classNetSocketStream" ],
    [ "PingPongPacket", "classPingPongPacket.html", "classPingPongPacket" ],
    [ "Player", "classPlayer.html", "classPlayer" ],
    [ "Plugin", "classPlugin.html", "classPlugin" ],
    [ "PluginsManager", "classPluginsManager.html", "classPluginsManager" ],
    [ "PNGFile", "classPNGFile.html", "classPNGFile" ],
    [ "Server", "classServer.html", "classServer" ],
    [ "ServerListPacket", "classServerListPacket.html", "classServerListPacket" ],
    [ "ServerSocket", "classServerSocket.html", "classServerSocket" ],
    [ "ServerStartEvent", "classServerStartEvent.html", null ],
    [ "UUID", "classUUID.html", "classUUID" ],
    [ "Vec", "classVec.html", "classVec" ],
    [ "ZLibStream", "classZLibStream.html", "classZLibStream" ]
];